---
title: "3/25"
output: html_document
---

```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
```
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum5 <- c(c(-1,5),c(2,3))
```

```{r}

vNum4 <- c() # 空向量
```
```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```

```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```
```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```
```{r}
typeof(num1Vector)
```
```{r}
char1<-"你好"
char2<-'你好'
heSAID<-"今天多了一粒受診"
```
```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/410773101a/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```
```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
```
```{r}
library(googlesheets4)
`出席狀況表單網址` <- ss # 缺乏定義值
 <-  ("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
homework_sheet <- sheets_read(ss,sheet=1)

                                  )
homework_sheet <- sheets_read(ss,sheet=1)
```
```{r}
library(googlesheets4)
`出席狀況表單網址` <-"https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645"  # 缺乏定義值
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <-  # 缺乏定義值
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```
```{r}
library(googlesheets4)
`出席狀況表單網址` <-  "https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645"
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1) 
```

